# Generated by Django 5.2.5 on 2025-10-12 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_mode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_mode.chat'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_asignado', to='game_mode.nivel'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
