# Generated by Django 5.2.5 on 2025-10-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_mode', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='tipo_entrevistador',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
