# Generated by Django 5.2.5 on 2025-10-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_mode', '0003_nivel_tipo_entrevistador'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='mensajes',
            field=models.JSONField(default=dict),
        ),
    ]
