# Generated by Django 5.2.5 on 2025-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_mode', '0004_chat_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
