# Generated by Django 5.2.5 on 2025-10-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_mode', '0005_chat_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='mensajes',
        ),
        migrations.AlterField(
            model_name='chat',
            name='resumen',
            field=models.JSONField(default=dict),
        ),
    ]
