# Generated by Django 5.2.5 on 2025-10-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_mode', '0006_remove_chat_mensajes_alter_chat_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progreso',
            name='pregunta_actual',
            field=models.IntegerField(default=1),
        ),
    ]
