# Generated by Django 5.2.7 on 2025-11-14 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('technical', 'Entrevista Técnica'), ('behavioral', 'Entrevista Conductual'), ('general', 'Entrevista General'), ('leadership', 'Liderazgo'), ('sales', 'Ventas'), ('customer_service', 'Atención al Cliente')], default='general', max_length=20)),
                ('title', models.CharField(default='Nueva Entrevista', max_length=200)),
                ('duration', models.CharField(choices=[('quick', 'Rápida (10 min)'), ('standard', 'Estándar (20 min)'), ('extended', 'Extendida (30 min)'), ('unlimited', 'Sin límite')], default='standard', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20)),
                ('focus_area', models.CharField(choices=[('communication', 'Comunicación'), ('problem_solving', 'Resolución de Problemas'), ('teamwork', 'Trabajo en Equipo'), ('adaptability', 'Adaptabilidad'), ('time_management', 'Gestión del Tiempo'), ('conflict_resolution', 'Resolución de Conflictos')], default='communication', max_length=30)),
                ('position_level', models.CharField(blank=True, help_text='Ej: Junior Developer, Senior Manager', max_length=100)),
                ('total_points', models.IntegerField(default=0)),
                ('current_level', models.CharField(default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Usuario'), ('bot', 'JoBot')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interview_mode.interviewsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('practice_dates', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
