# Generated by Django 5.2.7 on 2025-11-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_mode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='duration',
            field=models.CharField(choices=[('quick', 'Rápida (10 min)'), ('standard', 'Estándar (20 min)'), ('extended', 'Extendida (30 min)'), ('unlimited', 'Sin límite')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='focus_area',
            field=models.CharField(choices=[('communication', 'Comunicación'), ('problem_solving', 'Resolución de Problemas'), ('teamwork', 'Trabajo en Equipo'), ('adaptability', 'Adaptabilidad'), ('time_management', 'Gestión del Tiempo'), ('conflict_resolution', 'Resolución de Conflictos')], default='communication', max_length=30),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='position_level',
            field=models.CharField(blank=True, help_text='Ej: Junior Developer, Senior Manager', max_length=100),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'Entrevista Técnica'), ('behavioral', 'Entrevista Conductual'), ('general', 'Entrevista General'), ('leadership', 'Liderazgo'), ('sales', 'Ventas'), ('customer_service', 'Atención al Cliente')], default='general', max_length=20),
        ),
    ]
