# Generated by Django 5.2.8 on 2025-11-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_mode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_time_seconds',
            field=models.FloatField(blank=True, help_text='Tiempo en segundos que el usuario tardó en responder esta pregunta.', null=True),
        ),
    ]
