# Generated by Django 5.2.7 on 2025-11-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_mode', '0002_interviewsession_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='current_level',
            field=models.CharField(default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20),
        ),
    ]
