# Generated by Django 5.2.7 on 2025-11-14 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_mode', '0002_message_response_time_seconds'),
        ('interview_mode', '0004_userstreak'),
    ]

    operations = [
    ]
